/**
 * U3P1 - Aplicación que usa cola
 * @author 
 * Lozano Mora Juan Pablo
 * Rojano Meza Leonardo Gael 5A
 */

// Este es el JForm principal.

package forms;

import data.ColaCircularPedidos;
import data.Hora;
import data.Pedido;
import data.PedidoParser;
import javax.swing.JOptionPane;

public class MainForm extends javax.swing.JFrame {

    ColaCircularPedidos colaPedidos;
    
    public MainForm() {
        initComponents();
        
        colaPedidos = new ColaCircularPedidos(20);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        lbSubTitle = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbNombreCliente = new javax.swing.JLabel();
        jtfNombreCliente = new javax.swing.JTextField();
        lbIdPedido = new javax.swing.JLabel();
        jtfIdPedido = new javax.swing.JTextField();
        lbNombrePlatillo = new javax.swing.JLabel();
        jtfNombrePlatillo = new javax.swing.JTextField();
        lbCantidad = new javax.swing.JLabel();
        jtfCantidad = new javax.swing.JTextField();
        lbPrecio = new javax.swing.JLabel();
        jtfPrecio = new javax.swing.JTextField();
        lbHora = new javax.swing.JLabel();
        jtfHora = new javax.swing.JTextField();
        lbTipoCliente = new javax.swing.JLabel();
        jtfTipoCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taColaPedidos = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbTitleActualPedido = new javax.swing.JLabel();
        lbActualHora = new javax.swing.JLabel();
        lbActualPrioridad = new javax.swing.JLabel();
        lbActualPrecio = new javax.swing.JLabel();
        lbActualIdPedido = new javax.swing.JLabel();
        lbActualNombrePlatilloYCant = new javax.swing.JLabel();
        lbActualNombreCliente = new javax.swing.JLabel();
        btnPedidoCompletado = new javax.swing.JButton();
        btnImportarPedidos = new javax.swing.JButton();
        btnSubir = new javax.swing.JButton();
        btnExportarPedidos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(253, 242, 240));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbSubTitle.setFont(new java.awt.Font("DM Sans 18pt Black", 0, 14)); // NOI18N
        lbSubTitle.setForeground(new java.awt.Color(20, 5, 3));
        lbSubTitle.setText("Pantalla de Registro y Visualización de Pedidos");
        lbSubTitle.setFocusable(false);
        jPanel1.add(lbSubTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 370, -1));

        lbTitle.setFont(new java.awt.Font("Hubot Sans", 0, 28)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(20, 5, 3));
        lbTitle.setText("MyRestaurant");
        lbTitle.setFocusable(false);
        jPanel1.add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 440, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 760, 10));

        lbNombreCliente.setFont(new java.awt.Font("DM Sans 18pt", 0, 14)); // NOI18N
        lbNombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        lbNombreCliente.setText("Nombre del cliente");
        jPanel1.add(lbNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 150, 30));

        jtfNombreCliente.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jtfNombreCliente.setToolTipText("");
        jPanel1.add(jtfNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 200, 30));

        lbIdPedido.setFont(new java.awt.Font("DM Sans 18pt", 0, 14)); // NOI18N
        lbIdPedido.setForeground(new java.awt.Color(0, 0, 0));
        lbIdPedido.setText("ID del pedido");
        jPanel1.add(lbIdPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 30));

        jtfIdPedido.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jtfIdPedido.setToolTipText("");
        jPanel1.add(jtfIdPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 200, 30));

        lbNombrePlatillo.setFont(new java.awt.Font("DM Sans 18pt", 0, 14)); // NOI18N
        lbNombrePlatillo.setForeground(new java.awt.Color(0, 0, 0));
        lbNombrePlatillo.setText("Nombre del platillo");
        jPanel1.add(lbNombrePlatillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, 30));

        jtfNombrePlatillo.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jtfNombrePlatillo.setToolTipText("");
        jPanel1.add(jtfNombrePlatillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 200, 30));

        lbCantidad.setFont(new java.awt.Font("DM Sans 18pt", 0, 14)); // NOI18N
        lbCantidad.setForeground(new java.awt.Color(0, 0, 0));
        lbCantidad.setText("Cantidad");
        jPanel1.add(lbCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 150, 30));

        jtfCantidad.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jtfCantidad.setToolTipText("");
        jPanel1.add(jtfCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 200, 30));

        lbPrecio.setFont(new java.awt.Font("DM Sans 18pt", 0, 14)); // NOI18N
        lbPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lbPrecio.setText("Precio");
        jPanel1.add(lbPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 150, 30));

        jtfPrecio.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jtfPrecio.setToolTipText("");
        jPanel1.add(jtfPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 200, 30));

        lbHora.setFont(new java.awt.Font("DM Sans 18pt", 0, 14)); // NOI18N
        lbHora.setForeground(new java.awt.Color(0, 0, 0));
        lbHora.setText("Hora");
        jPanel1.add(lbHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 30));

        jtfHora.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jtfHora.setToolTipText("");
        jPanel1.add(jtfHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 200, 30));

        lbTipoCliente.setFont(new java.awt.Font("DM Sans 18pt", 0, 14)); // NOI18N
        lbTipoCliente.setForeground(new java.awt.Color(0, 0, 0));
        lbTipoCliente.setText("Tipo de Cliente");
        jPanel1.add(lbTipoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 150, 30));

        jtfTipoCliente.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        jtfTipoCliente.setToolTipText("");
        jPanel1.add(jtfTipoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 200, 30));

        taColaPedidos.setColumns(20);
        taColaPedidos.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        taColaPedidos.setForeground(new java.awt.Color(0, 0, 0));
        taColaPedidos.setRows(5);
        jScrollPane1.setViewportView(taColaPedidos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 380, 120));

        jLabel1.setText(" ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, -1, -1));

        jPanel2.setBackground(new java.awt.Color(209, 238, 135));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitleActualPedido.setFont(new java.awt.Font("DM Sans 24pt", 1, 14)); // NOI18N
        lbTitleActualPedido.setForeground(new java.awt.Color(0, 0, 0));
        lbTitleActualPedido.setText("Pedido Actual");
        jPanel2.add(lbTitleActualPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lbActualHora.setFont(new java.awt.Font("DM Sans 18pt", 0, 12)); // NOI18N
        lbActualHora.setForeground(new java.awt.Color(0, 0, 0));
        lbActualHora.setText("(hora)");
        jPanel2.add(lbActualHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, -1));

        lbActualPrioridad.setFont(new java.awt.Font("DM Sans 18pt", 0, 12)); // NOI18N
        lbActualPrioridad.setForeground(new java.awt.Color(0, 0, 0));
        lbActualPrioridad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbActualPrioridad.setText("(prioridad)");
        jPanel2.add(lbActualPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 160, -1));

        lbActualPrecio.setFont(new java.awt.Font("DM Sans 18pt", 0, 12)); // NOI18N
        lbActualPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lbActualPrecio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbActualPrecio.setText("$(precio)");
        jPanel2.add(lbActualPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 90, -1));

        lbActualIdPedido.setFont(new java.awt.Font("DM Sans 18pt", 0, 12)); // NOI18N
        lbActualIdPedido.setForeground(new java.awt.Color(0, 0, 0));
        lbActualIdPedido.setText("(id del pedido)");
        jPanel2.add(lbActualIdPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 160, -1));

        lbActualNombrePlatilloYCant.setFont(new java.awt.Font("DM Sans 18pt", 0, 12)); // NOI18N
        lbActualNombrePlatilloYCant.setForeground(new java.awt.Color(0, 0, 0));
        lbActualNombrePlatilloYCant.setText("(nom del platillo + cantidad)");
        jPanel2.add(lbActualNombrePlatilloYCant, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, -1));

        lbActualNombreCliente.setFont(new java.awt.Font("DM Sans 18pt", 0, 12)); // NOI18N
        lbActualNombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        lbActualNombreCliente.setText("(nombre del cliente)");
        jPanel2.add(lbActualNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, -1));

        btnPedidoCompletado.setBackground(new java.awt.Color(141, 232, 90));
        btnPedidoCompletado.setFont(new java.awt.Font("DM Sans 24pt SemiBold", 0, 14)); // NOI18N
        btnPedidoCompletado.setForeground(new java.awt.Color(0, 0, 0));
        btnPedidoCompletado.setText("COMPLETADO");
        btnPedidoCompletado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedidoCompletadoActionPerformed(evt);
            }
        });
        jPanel2.add(btnPedidoCompletado, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 140, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 380, 120));

        btnImportarPedidos.setBackground(new java.awt.Color(237, 155, 129));
        btnImportarPedidos.setFont(new java.awt.Font("DM Sans 24pt SemiBold", 0, 12)); // NOI18N
        btnImportarPedidos.setForeground(new java.awt.Color(0, 0, 0));
        btnImportarPedidos.setText("Importar pedidos");
        btnImportarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarPedidosActionPerformed(evt);
            }
        });
        jPanel1.add(btnImportarPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 180, -1));

        btnSubir.setBackground(new java.awt.Color(225, 83, 38));
        btnSubir.setFont(new java.awt.Font("DM Sans 24pt SemiBold", 0, 14)); // NOI18N
        btnSubir.setText("SUBIR");
        btnSubir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubir, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 350, 120, -1));

        btnExportarPedidos.setBackground(new java.awt.Color(237, 155, 129));
        btnExportarPedidos.setFont(new java.awt.Font("DM Sans 24pt SemiBold", 0, 12)); // NOI18N
        btnExportarPedidos.setForeground(new java.awt.Color(0, 0, 0));
        btnExportarPedidos.setText("Exportar pedidos");
        btnExportarPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarPedidosActionPerformed(evt);
            }
        });
        jPanel1.add(btnExportarPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    // BOTÓN ENCARGADO DE ELIMINAR UN PEDIDO AL COMPLETARSE
    private void btnPedidoCompletadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedidoCompletadoActionPerformed
        // Eliminar pedido de la cola
        colaPedidos.eliminar();
        
        // Actualizar TextArea de la Cola
        taColaPedidos.setText(colaPedidos.mostrar());
        
        // Actualizar valores del pedido actual
        showActualPedido();
    }//GEN-LAST:event_btnPedidoCompletadoActionPerformed

    
    // BOTÓN ENCARGADO DE IMPORTAR LA COLA DE PEDIDOS DE UN ARCHIVO DE TEXTO
    private void btnImportarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarPedidosActionPerformed
        // Instanciamos el parser
        PedidoParser parser = new PedidoParser();
        
        // Importamos
        ColaCircularPedidos colaPedidosImportada = parser.importFromFile();
        
        if (colaPedidosImportada != null) {
            JOptionPane.showMessageDialog(null, 
                "Se ha importado con éxito la cola de pedidos.", 
                "Cola importada", 
                JOptionPane.INFORMATION_MESSAGE);
            colaPedidos = colaPedidosImportada;
        }
        else JOptionPane.showMessageDialog(null, 
                "No fue posible exportar la cola de pedidos. \nEsto puede deberse a que no haya ningún archivo guardado o a un problema de memoria.", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        
        // Actualizar TextArea de la Cola
        taColaPedidos.setText(colaPedidos.mostrar());
        
        // Actualizar valores del pedido actual
        showActualPedido();
    }//GEN-LAST:event_btnImportarPedidosActionPerformed

    
    // BOTÓN ENCARGADO DE EXPORTAR LA COLA DE PEDIDOS A ARCHIVO DE TEXTO
    private void btnExportarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarPedidosActionPerformed
        // Instanciamos el parser
        PedidoParser parser = new PedidoParser();
        
        // Exportamos
        boolean result = parser.exportToFile(colaPedidos);
        if (result) JOptionPane.showMessageDialog(null, 
                "Se ha exportado con éxito la cola de pedidos.", 
                "Cola exportada", 
                JOptionPane.INFORMATION_MESSAGE);
        else JOptionPane.showMessageDialog(null, 
                "No fue posible exportar la cola de pedidos", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        
        // Al exportar se vacía la cola, pues no se puede acceder a los elementos
        // del medio si no se vacía antes.
        
        // Actualizar TextArea de la Cola
        taColaPedidos.setText(colaPedidos.mostrar());
        
        // Actualizar valores del pedido actual
        showActualPedido();
    }//GEN-LAST:event_btnExportarPedidosActionPerformed

    
    
    // BOTÓN ENCARGADO DE SUBIR UN PEDIDO
    private void btnSubirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirActionPerformed
        // Crear pedido según los JTextBox
        Pedido pedidoObtenido = getAllDataFromInput();
        if (pedidoObtenido == null) return;
        
        // Insertar pedido en la cola
        colaPedidos.insertar(pedidoObtenido);
        
        // Actualizar TextArea de la Cola
        taColaPedidos.setText(colaPedidos.mostrar());
        
        // Actualizar valores del pedido actual
        showActualPedido();
    }//GEN-LAST:event_btnSubirActionPerformed

    
    
    // MÉTODOS AUXILIARES
    
    // Método getAllDataFromInput()
    // Obtiene todos los valores de los JTextBox de la sección de Subir y
    // crea un objeto Pedido en base en ellos. Si hay algún valor inválido
    // muestra un mensaje de error y retorna un null.
    private Pedido getAllDataFromInput(){
        // Obtener todos los valores de los JTextBox
        String nombreCliente = jtfNombreCliente.getText();
        String idPedido = jtfIdPedido.getText();
        String nombrePlatillo = jtfNombrePlatillo.getText();
        
        int cantidad;
        try {
            cantidad = Integer.parseInt(jtfCantidad.getText());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, 
                    "Por favor, introduzca un número válido en el apartado de \"Cantidad\".", 
                    "Cantidad Inválida", 
                    JOptionPane.ERROR_MESSAGE);
            return null;
        }
        
        double precio;
        try {
            precio = Double.parseDouble(jtfPrecio.getText());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, 
                    "Por favor, introduzca un número válido en el apartado de \"Precio\".", 
                    "Precio Inválido", 
                    JOptionPane.ERROR_MESSAGE);
            return null;
        }
        
        Hora hora;
        try {
            hora = new Hora(jtfHora.getText());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, 
                    "Por favor, introduzca una hora válida en formato 24h \"16:15\" en el apartado de \"Hora\".", 
                    "Hora Inválida", 
                    JOptionPane.ERROR_MESSAGE);
            return null;
        }
        
        int prioridad;
        try {
            prioridad = Integer.parseInt(jtfTipoCliente.getText());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, 
                    "Por favor, introduzca un número válido en el apartado de \"Tipo de Cliente\".", 
                    "Prioridad Inválida", 
                    JOptionPane.ERROR_MESSAGE);
            return null;
        }
        
        // Comprobación de que todos los demás espacios están llenos
        if (nombreCliente.equals("")
                || idPedido.equals("")
                || nombrePlatillo.equals("") 
                || cantidad <= 0
                || precio <= 0
                || prioridad < 0){
            JOptionPane.showMessageDialog(null, 
                    "Por favor, llene todos los espacios requeridos con valores válidos.", 
                    "Valores Inválidos", 
                    JOptionPane.ERROR_MESSAGE);
            return null;
        }
        
        Pedido pedidoObtenido = new Pedido(nombreCliente,
        idPedido,
        nombrePlatillo,
        cantidad,
        precio,
        hora,
        prioridad);
        
        return pedidoObtenido;
    }
    
    // Método showActualPedido(){
    // Muestra los datos del pedido a completar, es decir, el último elemento
    // en la cola.
    private void showActualPedido(){
        Pedido pedidoActual = colaPedidos.front();
        
        if (pedidoActual == null){
            // Esto implica que la cola está vacía, por lo que ponemos valores
            // por default en el pedido actual.
            setDefaultActualPedido();
            return;
        }
        
        // Actualizamos valores del pedido actual.
        lbActualNombreCliente.setText(pedidoActual.getNombreCliente());
        lbActualIdPedido.setText(pedidoActual.getIdPedido());
        lbActualNombrePlatilloYCant.setText(pedidoActual.getNombrePlatillo() + " (" + pedidoActual.getCantidad() + ")");
        lbActualHora.setText(pedidoActual.getHora().getHora("HH:MM"));
        lbActualPrioridad.setText("Prioridad " + pedidoActual.getPrioridad());
        lbActualPrecio.setText("$" + pedidoActual.getPrecio());        
    }
    
    private void setDefaultActualPedido(){
        lbActualNombreCliente.setText("(nombre del cliente)");
        lbActualIdPedido.setText("(id del pedido)");
        lbActualNombrePlatilloYCant.setText("(nom del pedido + cantidad)");
        lbActualHora.setText("(hora)");
        lbActualPrioridad.setText("(prioridad)");
        lbActualPrecio.setText("$(precio)");
    }
    
    // Metodo exportColaToFile()
    // Este método se encarga de convertir todos los pedidos de la cola
    // a un archivo de texto.
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarPedidos;
    private javax.swing.JButton btnImportarPedidos;
    private javax.swing.JButton btnPedidoCompletado;
    private javax.swing.JButton btnSubir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jtfCantidad;
    private javax.swing.JTextField jtfHora;
    private javax.swing.JTextField jtfIdPedido;
    private javax.swing.JTextField jtfNombreCliente;
    private javax.swing.JTextField jtfNombrePlatillo;
    private javax.swing.JTextField jtfPrecio;
    private javax.swing.JTextField jtfTipoCliente;
    private javax.swing.JLabel lbActualHora;
    private javax.swing.JLabel lbActualIdPedido;
    private javax.swing.JLabel lbActualNombreCliente;
    private javax.swing.JLabel lbActualNombrePlatilloYCant;
    private javax.swing.JLabel lbActualPrecio;
    private javax.swing.JLabel lbActualPrioridad;
    private javax.swing.JLabel lbCantidad;
    private javax.swing.JLabel lbHora;
    private javax.swing.JLabel lbIdPedido;
    private javax.swing.JLabel lbNombreCliente;
    private javax.swing.JLabel lbNombrePlatillo;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JLabel lbSubTitle;
    private javax.swing.JLabel lbTipoCliente;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JLabel lbTitleActualPedido;
    private javax.swing.JTextArea taColaPedidos;
    // End of variables declaration//GEN-END:variables
}
